networks:
  home8:
    driver: bridge
    name: home8_stack

volumes:
  mysql_0.data:
    name: mysql_0.data
  mysql_1.data:
    name: mysql_1.data
  mysql_2.data:
    name: mysql_2.data

services:
  mysql_0:
    image: mysql:latest
    container_name: mysql_0
    restart: always
    ports:
      - "3308:3306"
    env_file:
      - env.mysql
    networks:
      home8:
        aliases:
          - mysql_0.local
    volumes:
      - mysql_0.data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./users.txt:/usr/share/mysql/sql/users.txt
      - ./mysql_with_flush_log_0.cnf:/etc/mysql/conf.d/mysql.cnf

  mysql_1:
    image: mysql:latest
    container_name: mysql_1
    restart: always
    ports:
      - "3306:3307"
    env_file:
      - env.mysql
    environment:
      MYSQL_TCP_PORT: 3307
    networks:
      home8:
        aliases:
          - mysql_1.local
    volumes:
      - mysql_1.data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./users.txt:/usr/share/mysql/sql/users.txt
      - ./mysql_with_flush_log_1.cnf:/etc/mysql/conf.d/mysql.cnf

  mysql_2:
    image: mysql:latest
    container_name: mysql_2
    restart: always
    ports:
      - "3307:3308"
    env_file:
      - env.mysql
    environment:
      MYSQL_TCP_PORT: 3308
    networks:
      home8:
        aliases:
          - mysql_2.local
    volumes:
      - mysql_2.data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./users.txt:/usr/share/mysql/sql/users.txt
      - ./mysql_with_flush_log_2.cnf:/etc/mysql/conf.d/mysql.cnf

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    env_file:
      - env.phpmyadmin
    networks:
      home8:
        aliases:
          - phpmyadmin.local
    depends_on:
      - mysql_0
      - mysql_1
      - mysql_2

  aspnetapp:
    container_name: aspnetapp
    image: aspnetapp:latest
    build:
      context: .
      dockerfile: ./WebApplication/WebApplication/Dockerfile
    environment:
      - "ConnectionStrings__Log=server=mysql_0.local;port=3306;user=root;password=root;database=home4db"
      - "ConnectionStrings__Log1=server=mysql_1.local;port=3307;user=root;password=root;database=home4db"
      - "ConnectionStrings__Log2=server=mysql_2.local;port=3308;user=root;password=root;database=home4db"
    ports:
      - '8082:80'
    networks:
      home8:
        aliases:
          - aspnetapp.local
    depends_on:
      - mysql_0
      - mysql_1
      - mysql_2
